---
- name: delete httpd pkg
  hosts: webservers
  become: true
  tasks:
    - name: stoppe httpd service
      service:
        name: httpd
        state: stopped

    - name: uninstall Httpd pkg
      yum:
       name: httpd
       state: removed      

