---
- name: install packages
  hosts: all
  become: true
    
  tasks:
    - name: install httpd pkg
      yum:
        name: httpd
        state: installed
      
    - name: start httpd service
      service:
          name: httpd
          state: started     

